"""create research tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-21 19:53:00.710560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('keyword_text', sa.Text(), nullable=False),
    sa.Column('normalized_keyword', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword')),
    sa.UniqueConstraint('normalized_keyword', 'language_code', name='uq_keyword_normalized_keyword_language_code')
    )
    op.create_table('research_project',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('seed_keyword', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_project'))
    )
    op.create_table('keyword_metric_snapshot',
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('research_id', sa.Uuid(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('estimated_monthly_searches', sa.BigInteger(), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('competition', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('competition_level', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_version', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], name=op.f('fk_keyword_metric_snapshot_keyword_id_keyword'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_id'], ['research_project.id'], name=op.f('fk_keyword_metric_snapshot_research_id_research_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_metric_snapshot'))
    )
    op.create_index(op.f('ix_keyword_metric_snapshot_keyword_id'), 'keyword_metric_snapshot', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_metric_snapshot_research_id'), 'keyword_metric_snapshot', ['research_id'], unique=False)
    op.create_table('research_keyword',
    sa.Column('research_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], name=op.f('fk_research_keyword_keyword_id_keyword'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_id'], ['research_project.id'], name=op.f('fk_research_keyword_research_id_research_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_keyword')),
    sa.UniqueConstraint('research_id', 'keyword_id', name='uq_research_keyword_research_id_keyword_id')
    )
    op.create_index(op.f('ix_research_keyword_keyword_id'), 'research_keyword', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_research_keyword_research_id'), 'research_keyword', ['research_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_keyword_research_id'), table_name='research_keyword')
    op.drop_index(op.f('ix_research_keyword_keyword_id'), table_name='research_keyword')
    op.drop_table('research_keyword')
    op.drop_index(op.f('ix_keyword_metric_snapshot_research_id'), table_name='keyword_metric_snapshot')
    op.drop_index(op.f('ix_keyword_metric_snapshot_keyword_id'), table_name='keyword_metric_snapshot')
    op.drop_table('keyword_metric_snapshot')
    op.drop_table('research_project')
    op.drop_table('keyword')
    # ### end Alembic commands ###
